apiVersion: v1
kind: Pod
metadata:
  name: pod-241
spec:
  containers:
  - name: pod-241
    image: 192.168.1.52/system_containers/alpine:3.7
    command: ["sh", "-c", "while true; do echo 'ok'; sleep 1; done;"]
    volumeMounts:
    - name: iscsi
      mountPath: /mnt
  volumes:
  - name: iscsi
    persistentVolumeClaim:
      claimName: pvc-241
